### PR TITLE
Fixes for spike train threshold detection

### PR DESCRIPTION
**Pull request by rgerkin**
Described in #54.

### CODE REVIEW

**Comment by apdavison** [comment]
Hi Rick, please could you squash these into a smaller number of commits? At the least all the commits with the same message should be squashed.

**Comment by rgerkin** [comment]
Whoops, sorry.  Should be fixed now.

**Comment by apdavison** [comment]
There are still seeing 23 commits for a small number of final changes, which will make it hard in future to figure out what changed and why.

I think it would be better to close this PR, make a new branch off the current master, then apply the changes in a single commit to the new branch and open a new PR.

**Comment by rgerkin** [comment]
Git inexplicably changed the commit hashes for a bunch of old commits when I squashed some newer commits together.  I don't understand this.  I'll take your advice and submit a new pull request tonight.

**Comment by rgerkin** [comment]
Re-opening with sensible commit log

**Pull request closed without merging**
