### PR TITLE
[MAIN] Fix typos and grammatical errors in GPFA tutorial

### PR DESCRIPTION
**Pull request by kushaangupta**

### CODE REVIEW

**Review by Moritz-Alexander-Kern — CHANGES_REQUESTED** [review]
Hey @kushaangupta ,
thanks for helping to improve the GPFA tutorial.

It seems in the first code cell the following lines were removed unintentionally ?!
See: https://elephant--587.org.readthedocs.build/en/587/tutorials/gpfa.html

```python
def integrated_lorenz(dt, num_steps, x0=0, y0=1, z0=1.05,
                      sigma=10, rho=28, beta=2.667, tau=1e3):
    """

    Parameters
    ----------
    dt :
        Integration time step in ms.
```

The other changes look good to me :100: .

**Comment by kushaangupta** [comment]
Hi @Moritz-Alexander-Kern , sorry about that error. I've fixed it now. Also, I also see that the plots in the second half of tutorial, GPFA on Lorentz system haven't been rendered in the uploaded notebook. Should I fix that or are they intentionally not plotted?

**Comment by Moritz-Alexander-Kern** [comment]
Hi @kushaangupta ,
I appreciate you bringing this to my attention. I must admit that I overlooked the fact that the second half of the notebook was not executed. 
Would you kindly execute the entire notebook and push the executed version? 
Feel free to also delete the last two cells of the notebook. 
One of the cells is empty, and the other one only contains the code `print(scipy.__version__)`. These cells are no longer needed, so removing them will help keep the notebook clean and concise. 
Thank you for your help. :slightly_smiling_face:

**Comment by kushaangupta** [comment]
I pushed the fix

**Review by Moritz-Alexander-Kern — APPROVED** [review]
Approved, thanks @kushaangupta .

**Comment by Moritz-Alexander-Kern** [comment]
Failing unit tests fixed: #588

**Pull request merged**
