### PR TITLE
Minor release 0.6.2

### PR DESCRIPTION
**Pull request by mdenker**
This is a follow-up release to 0.6.1, adding two more functions and a number of remaining bug fixes not related to the breaking changes of Neo 0.7.x.

### CODE REVIEW

**Comment by jpgill86** [comment]
Is this release being held up by #216?

**Comment by mdenker** [comment]
I just closed the issue assuming it to be addressed by #217.

**Comment by jpgill86** [comment]
Thank you @mdenker!

**Comment by mdenker** [comment]
Should be available on pypi and rtd now... Thanks for your help @jpgill86 !

**Pull request merged**
