### PR TITLE
Spike Train Extraction from Analog Signals via Threshold Detection

### PR DESCRIPTION
**Pull request by rgerkin**
Addresses #43.  Also added little Izhikevich neuron simulator for generation of membrane potential waveforms for testing the new threshold_detection function.  This simulator could potentially be moved elsewhere.  I thought it was better to simulate real-looking waveforms though, since it will be easier to create a larger collection of robust spike detection tests e.g. on different spike neuron classes.  I only added one test based on a tonic firing neuron.

### CODE REVIEW

**Comment by apdavison** [comment]
I think having the Izhikevich generator is not a bad idea, but it needs its own unit tests. Can I suggest you generate some test voltage traces using a reference simulator such as NEST, and use these for unit testing?

**Comment by rgerkin** [comment]
@apdavison Good idea but would it be possible to merge everything except bbf88f2 for the time being?  Then I can get NeuralEnsemble:master into my projects.  Or would that not be OK since bbf88f2 contains, for now, the only test of the spike extraction code?

**Comment by rgerkin** [comment]
@apdavison Another question is whether you want any unit tests to depend upon a NEST installation (this will add 10+ minutes to every Travis run).  Maybe a lighter-weight reference simulator?

**Comment by rgerkin** [comment]
@apdavison Brian2, maybe?  Avoids too many dependencies, Python3 compatible, active development.  Not part of PyNN yet, though, right.

**Comment by apdavison** [comment]
I was suggesting that you use NEST to generate some test data, and add those to the repository. The test would then compare the results of the Izhikevich mini-simulator against the pre-recorded data, not against NEST directly.

**Comment by rgerkin** [comment]
@apdavison OK, got it.

**Comment by rgerkin** [comment]
@apdavison OK that's all taken care of.  I used Brian2 to generate the test data though since NEST was not compiling on my machine.  Documented [here](https://github.com/neuroelectro/elephant/blob/master/elephant/test/make_spike_extraction_test_data.py) which is part of 456ebac

**Pull request merged**
