### PR TITLE
Added ASSET code + unittests

### PR DESCRIPTION
**Pull request by etorre**
This pull request adds an analysis known as ASSET (analysis of sequences of synchronous events) which searches sequences of synchronous spikes in parallel spike trains ("synfire-like activity"), tests their statistical significance, and reconstructs the chain of neuron groups that participated in the activity.

### CODE REVIEW

**Comment by alperyeg** [comment]
Ah yes, I totally forgot to say that the build is going to fail since we do not have scitkit learn in the dependicies list. We need to make scikit learn optional as we do for pandas.

**Comment by etorre** [comment]
You're right. I just added the optional dependency to requirements.txt:
#sklearn>=0.15.1
and rebased the log history. Have a look and let me know

**Comment by alperyeg** [comment]
No I meant something like  [this](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/test/test_pandas_bridge.py) and for the install script we need to add an optional settings [here](https://github.com/NeuralEnsemble/elephant/blob/master/continuous_integration/install.sh) and [here](https://github.com/NeuralEnsemble/elephant/blob/master/.travis.yml). I can take of that later.

**Comment by alperyeg** [comment]
@apdavison Do you know why Travis is not running on this pull request any more? Very strange...

**Pull request merged**
