### PR TITLE
Fix documentation, remove version cap on sphinxcontrib-bibtex

### PR DESCRIPTION
**Pull request by Moritz-Alexander-Kern**
This PR removes the version cap on `sphinxcontrib-bibtex==1.0.0`.

Newer versions of `sphinxcontrib-bibtex` require the path to the `.bib` file to be specified in the configuration file for the documentation (conf.py).  

- removed version cap for `sphinxcontrib-bibtex`
- added path to `viziphant.bib` file to `conf.py`
- removed html4 writer, since Issue https://github.com/sphinx-doc/sphinx/issues/6705#issuecomment-536197438 is resolved and html4 is deprecated with newer versions of sphinx. https://github.com/readthedocs/sphinx_rtd_theme/pull/1091

See docs here: https://elephant-docs-development.readthedocs.io/en/fix-bibtex-contrib-version-cap/modules.html

### CODE REVIEW

**Review by Moritz-Alexander-Kern — COMMENTED** [review]
build wheels

**Comment by Moritz-Alexander-Kern** [comment]
With version 2.2.0 the reference style can be changed:

> To configure your referencing style, an optional config setting bibtex_reference_style has been added. If not specified, this defaults to the label style, which will use the label to format citation references, matching the referencing style as in previous versions. The other style currently available is author_year, for author-year style referencing.


See: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/changes.html

**Comment by Moritz-Alexander-Kern** [comment]
For a sample of the new citation style, aswell as the new bibliography style, see:
https://elephant--523.org.readthedocs.build/en/523/reference/spade.html

# Citation:
image

# Bibliography:
image

**Review by Moritz-Alexander-Kern — COMMENTED** [review]
build wheels

**Review by Moritz-Alexander-Kern — COMMENTED** [review]
build wheels

**Review by mdenker — APPROVED** [review]

**Pull request merged**
