### PR TITLE
Added the spike time tiling coefficient

### PR DESCRIPTION
**Pull request by FMendezSlc**
A function to calculate the Spike Time Tiling Coefficient (STTC) as proposed by (Cutts and Eglen, 2014) and following C. Cutts implementation in C.

### CODE REVIEW

**Comment by alperyeg** [comment]
@FMendezSlc first thanks for the contribution. I have some remarks in general.
* Unittests are missing, please have a look at other unittests e.g. [here](https://github.com/NeuralEnsemble/elephant/blob/master/elephant/test/test_spike_train_correlation.py) 
* The code is not pep8 conform, you could use tools like autopep to format the code/documentation. Also the naming of variables or function names are related to it. Later I can make more detailed comments. 

I didn't have a look at the code in detail and would like to have @pietroquaglio to check it.

**Comment by alperyeg** [comment]
@FMendezSlc I created a pull request with some additions and modifications to your branch. Please have a look.

**Comment by mdenker** [comment]
I suggest to merge this code and add unit tests in a second follow-up pull request

**Comment by mdenker** [comment]
@FMendezSlc Could you please let us know how we can acknowledge you in the `doc/authors.rst` file (either send a message, or make a pull request to directly enter your name/affill in the file). Thanks again for your contribution!

@alperyeg Please feel free to make a PR with your unit tests to the STTC.

**Comment by mdenker** [comment]
Great, thanks! We merged your code and will include the unit tests. We'll include your name in the author list in the upcoming release these days. All the best to Mexico!

**Pull request merged**
