### PR TITLE
Fix *CSD methods/tests

### PR DESCRIPTION
**Pull request by espenhgn**
Fixes some issues related to `neo.AnalogSignal` assumes signal shape `(# timesteps, # nchannels)`

### CODE REVIEW

**Comment by espenhgn** [comment]
Suggest @ccluri take a look.

**Comment by alperyeg** [comment]
@espenhgn the fixes look fine. I can merge if you want. 
@ccluri further any input on this?

**Comment by ccluri** [comment]
@espenhgn : https://github.com/espenhgn/elephant/blob/a7d78489bee4d1e2a4443ade9bb211d43f232f94/elephant/current_source_density.py#L238 minor fix to the documentation.

Otherwise okay with the PR.

Does this break backward compatibility with neo 0.4? 
For future reference, the reason for the inputs to be list(neo.analogsignal) was mentioned here - point number 6 here - https://github.com/NeuralEnsemble/elephant/pull/93#issuecomment-249233213

**Comment by alperyeg** [comment]
> Does this break backward compatibility with neo 0.4?

The `AnalogSignal` was replaced in `v0.5` with the `AnalogSignalArray`. So it depends what you do with the returned output, if it was formatted correctly then it should not make a problem. Regarding the coordinates (your point 6) there is not (probably will not in the future) an ultimate solution to have a consistent mapping. Maybe one could think to have a mapping in the annotations?

**Comment by espenhgn** [comment]
Hi,
I fixed the docstring @ccluri pointed out. 
@alperyeg, your comment confuses me. I'm using neo 0.5.2, and there is no AnalogSignalArray class, only AnalogSignal. 

I'm fine with merging.

**Comment by alperyeg** [comment]
Yes it is confusing. What I meant is the internal representation of the AnalogSignal.

**Comment by espenhgn** [comment]
@alperyeg Ok, I understand.

**Pull request merged**
