### PR TITLE
Change signal's `duplicate_with_new_array` to `duplicate_with_new_data`

### PR DESCRIPTION
**Pull request by jpgill86**
For compatibility with Neo 0.7.0 (soon to be released)

### CODE REVIEW

**Comment by jpgill86** [comment]
Unless a more clever approach is taken in which the method called is determined dynamically depending on which version of Neo is installed, `requirements.txt` will need bumped too. I can try that after Neo 0.7.0 is officially released to see if the Travis tests pass.

**Comment by jpgill86** [comment]
Actually, I think there will be many more changes needed if elephant is going to support Neo 0.7.0 fully, which changed a lot more than the name of this one method.

**Comment by mdenker** [comment]
Cool, thanks for the quick response to this breaking issue. I can confirm your fix passes the corresponding tests on my machine with the upcoming Neo 0.7 code.

As you expect, there are a few other issues that arise, in particular an issue in the instantaneous rate, spike train correlation, as well as in the `neo_utils` module. It seems at first glance that at least some of these issues have to do with changes in the way `t_start` and `t_stop` are handled when rescaling a spike train. Previously, `t_start` and `t_stop` where scaled along with the spike times, in 0.7. this behavior seems changed and the start and stop are left alone (which may be rather the desired behavior). Requires more investigation, though...

**Comment by mdenker** [comment]
The `t_start` and `t_stop` issue breaking some of Elephant's tests is now handled in 
https://github.com/NeuralEnsemble/python-neo/issues/613
https://github.com/NeuralEnsemble/python-neo/pull/614

**Comment by jpgill86** [comment]
To handle the breaking change described here (Neo's `AnalogSignal.duplicate_with_new_array` was renamed to `AnalogSignal.duplicate_with_new_data` in 0.7.0), we could try to preserve backwards compatibility with older versions of Neo by dynamically using one name or the other depending on which version is installed. Is it worth it?

Since Neo 0.7.0 is live on PyPI, I'm going to, for now, try the simpler thing in this PR and just bump the Neo requirement to 0.7.0, and then we can see how the Travis tests fare.

**Comment by mdenker** [comment]
Yes, the version number must be fixed. I think this is reasonable, since Neo and Elephant are coupled so strongly, that "hot fixes" will not be a good idea at this stage. 

However, we considered to make matching releases of the next major versions, i.e., fixing Elephant to use
```
neo>=0.7.0,<0.8.0
```
such that the future Neo releases up to Neo 1.0.0 (which are likely to have considerable enhancements) will not break Elephant.

**Comment by jpgill86** [comment]
Alright, that sounds reasonable. I'm going to remove the change to `requirements.txt` from this PR since that seems to be part of a larger discussion and requires the coordination of multiple fixes.

**Comment by mdenker** [comment]
Ok, yes, that makes sense. Will merge this fix as is.

**Comment by mdenker** [comment]
This PR was merged and extended into cumulativ fix #203 to test CI pass.

**Comment by mdenker** [comment]
Neo Version number of upcoming 0.6.1 will be fixed to >=0.7.0 and <0.8.0 to prevent similar breaks on 0.8.0 release.

**Pull request closed without merging**
